# Generated by Django 5.0.1 on 2024-04-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_section_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('post', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
